subor = open("tabulka_pocetnosti.txt","r").read()
array = []
array.append(subor)
print(array)

for i in array[0]:
    a = array[0].count('A') + array[0].count('a')
    b = array[0].count('B') + array[0].count('b')
    c = array[0].count('C') + array[0].count('c')
    d = array[0].count('D') + array[0].count('d')
    e = array[0].count('E') + array[0].count('e')
    f = array[0].count('F') + array[0].count('f')
    g = array[0].count('G') + array[0].count('g')
    h = array[0].count('H') + array[0].count('h')
    i = array[0].count('I') + array[0].count('i')
    j = array[0].count('J') + array[0].count('j')
    k = array[0].count('K') + array[0].count('k')
    l = array[0].count('L') + array[0].count('l')
    m = array[0].count('M') + array[0].count('m')
    n = array[0].count('N') + array[0].count('n')
    o = array[0].count('O') + array[0].count('o')
    p = array[0].count('P') + array[0].count('p')
    q = array[0].count('Q') + array[0].count('q')
    r = array[0].count('R') + array[0].count('r')
    s = array[0].count('S') + array[0].count('s')
    t = array[0].count('T') + array[0].count('t')
    u = array[0].count('U') + array[0].count('u')
    v = array[0].count('V') + array[0].count('v')
    w = array[0].count('W') + array[0].count('w')
    x = array[0].count('X') + array[0].count('x')
    y = array[0].count('Y') + array[0].count('y')
    z = array[0].count('Z') + array[0].count('z')
print("A -",a)
print("B -",b)
print("C -",c)
print("D -",d)
print("E -",e)
print("F -",f)
print("G -",g)
print("H -",h)
print("I -",i)
print("J -",j)
print("K -",k)
print("L -",l)
print("M -",m)
print("N -",n)
print("O -",o)
print("P -",p)
print("Q -",q)
print("R -",r)
print("S -",s)
print("T -",t)
print("U -",u)
print("V -",v)
print("W -",w)
print("X -",x)
print("Y -",y)
print("Z -",z)
